### ISSUE TITLE
tag <svg> and <use> missing

### ISSUE THREAD

**Issue by Runik51ua** [TYPO3/html-sanitizer#43]
missing svg and use tag

According to #23 

![image](https://user-images.githubusercontent.com/50318376/130231173-4375194a-c532-4f73-988b-ea90f3b77415.png)

**Comment by ohader** [comment]
I found the following counter parts on the corresponding website.
Can you please explain a little bit, how those SVG arrows are added? Does that happen in CKEditor/RTE already or using some post-processing in TypoScript? In case it's TypoScript, please share the TypoScript.

In general `xlink:href` can be misused as well - thus, it probably would be better to separate user-submitted content from post-processing (in case it's done like that).

```html
<div class="ce-bodytext">
    ...
    <p>
        <a href="/kontakt/ansprechpartner/lsi-arabicum" class="Formatting--arrow">...
            <svg class="Formatting--arrow_icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16.016 11.956">
                <path id="icon-arrow-orange_Pfad_374" data-name="Pfad 374"
                      d="M19.208,22.912l-.98-.924,4.452-4.4H8.96V16.3H22.68l-4.424-4.48.952-.868,5.768,5.8v.364Z"
                      transform="translate(-8.96 -10.956)" fill="#f80"></path>
            </svg>
        </a>
    </p>
    <p>Ihre Ansprechpartner und -partnerinnen in der
        <strong><a href="/kontakt/kursverwaltung" class="Formatting--arrow">
            Kursverwaltung
            <svg class="Formatting--arrow_icon" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16.016 11.956">
                <path id="icon-arrow-orange_Pfad_374" data-name="Pfad 374"
                      d="M19.208,22.912l-.98-.924,4.452-4.4H8.96V16.3H22.68l-4.424-4.48.952-.868,5.768,5.8v.364Z"
                      transform="translate(-8.96 -10.956)" fill="#f80"></path>
            </svg>
        </a></strong><a href="/kontakt/kursverwaltung" class="Formatting--arrow">
            <svg class="Formatting--arrow_icon" xmlns="http://www.w3.org/2000/svg"></svg>
            <strong></strong>
            <use xlink:href="/typo3conf/ext/lsi_templates/Resources/Public/dist/icons.svg#icon-arrow-orange"></use>
            <strong></strong></a></p>
</div>
```

**Comment by Runik51ua** [comment]
svg was added via CKEditor/RTE, also i tested ` xlink:href ` works fine.

**Comment by ohader** [comment]
> svg was added via CKEditor/RTE, also i tested `xlink:href` works fine.

In case it would have been added automatically for every link (`<a>` tag) using `stdWrap.parseFunc`, there would have been possibilities to solve it. However, allowing arbitrary `<svg><use xlink:href="..."` as input to rich-text fields also allows cross-site scripting - potential exploits are described in these links:

* https://snyk.io/vuln/npm:angular:20151205
* https://insert-script.blogspot.com/2020/09/xss-challenge-solution-svg-use.html
* https://github.com/darylldoyle/svg-sanitizer/blob/master/tests/data/xlinkLaughsTest.svg - attention, might crash your browser

In general SVG would have to be sanitized through https://github.com/darylldoyle/svg-sanitizer, since it is capable of detecting those `<use>` recursions.

As mentioned about, allowing arbitrary `<svg><use xlink:href="..."` allows cross-site-scripting as well - which contradicts the goals of this library. Alternatives to `<svg><use xlink:href="..."` might be using `<img src="sprites.svg#identifier">` as described at https://gist.github.com/darsain/3a8e344f655621ce1d4f

**Comment by Runik51ua** [comment]
okay, thank you for your explanation

> > svg was added via CKEditor/RTE, also i tested `xlink:href` works fine.
> 
> In case it would have been added automatically for every link (`<a>` tag) using `stdWrap.parseFunc`, there would have been possibilities to solve it. However, allowing arbitrary `<svg><use xlink:href="..."` as input to rich-text fields also allows **cross-site scripting** - potential exploits are described in these links:
> 
> * https://snyk.io/vuln/npm:angular:20151205
> * https://insert-script.blogspot.com/2020/09/xss-challenge-solution-svg-use.html
> * https://github.com/darylldoyle/svg-sanitizer/blob/master/tests/data/xlinkLaughsTest.svg - attention, might crash your browser
> 
> In general SVG would have to be sanitized through https://github.com/darylldoyle/svg-sanitizer, since it is capable of detecting those `<use>` recursions.
> 
> As mentioned about, **allowing arbitrary `<svg><use xlink:href="..."` allows cross-site-scripting** as well - which contradicts the goals of this library. Alternatives to `<svg><use xlink:href="..."` might be using `<img src="sprites.svg#identifier">` as described at https://gist.github.com/darsain/3a8e344f655621ce1d4f

okay, thank you for your explanation
